version: '3'

services:
    node:        
        image: node
        volumes:
            - .:/workspace:delegated
        stdin_open: true
        tty: true
        ports: 
            - 53000:53000
    